name: Azure Inventory Automation

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  run-ari:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libgdiplus libc6-dev

    - name: Install PowerShell Modules
      shell: pwsh
      run: |
        Install-Module Az -Force -Scope CurrentUser
        Install-Module AzureResourceInventory -Force -Scope CurrentUser

    - name: Run ARI Script
      shell: pwsh
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        ./scripts/RunARI.ps1

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: AzureInventoryReport
        path: reports/*.xlsx

    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 587
        secure: false
        
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        
        subject: Azure Inventory Report
        
        to: |
          yogeshkhairnar@synergetics-consulting.com
          
          
        cc: |
          sumitlad@synergetics-consulting.com
  
          
        from: Azure Inventory Automation
        
        body: |
          Hello Team,
          Please find attached latest Azure Resource Inventory Report.
          
          Regards,
          Yogesh

        attachments: reports/*.xlsx
    







